### ISSUE TITLE
Automatically create a root span if none is present.

### ISSUE THREAD

**Issue by semtexzv** [tikv/minitrace-rust#176]
I'm working on an app that has long running futures. It seems that minitrace does not report anything If I don't create a root span. Which is kind of impossible, since my root future has the runtime of the program.

It'd be nice if the `#[minitrace::trace]` macro would create root span if none is present.

**Comment by andylokandy** [comment]
We have previously experimented with the automatic creation of root spans in several major versions. Initially, we believed that as long as all spans were reported, the results would be satisfactory. However, this was not the case; the automatically created spans resembled stray straws scattered across a field - isolated and randomly appearing everywhere without any parent or child connections.

We eventually understood that if a root span is missing due to negligence, it's an error that needs rectification by correctly adding the root span.

For long-running tasks, there's a recommended practice: maintain a lengthy root span for these tasks and substitute it with a new one at certain intervals or after several 'polls'. This method provides optimal control over reporting behavior and yields visually appealing results in Jaeger.
