### ISSUE TITLE
is it possible to create multiple instances of the collector?

### ISSUE THREAD

**Issue by dotansimha** [tikv/minitrace-rust#178]
I'm looking for a tracing lib alternative, and `minitrace` seems super impressive! 💪 

I was wondering if there's a way to create multiple collectors. my goal is to implement some kind of multi-tenant tracing? (for example, a separate tracing config per each endpoint or component in a server).

I noticed that currently there's only a single global collector and it's not scoped? (set with `minitrace::set_reporter`)

Alternatively, is there any way of creating multiple filtered reporters? 

Thanks!

**Comment by andylokandy** [comment]
Currently, the library is designed with a single global collector to prioritize performance. This means that configuring distinct collector behaviors for each trace isn't directly supported due to this design trade-off. 

However, it's worth trying out the default configuration to see if it meets your requirements or becomes a performance bottleneck. 

Additionally, the [Span::root()](https://docs.rs/minitrace/latest/minitrace/struct.Span.html#method.cancel) method does provide some control over trace-level behavior. One possible workaround to achieve multi-tenant tracing could be to split traces of different components into separate roots. You can do this by connecting them with `Span::root("root", SpanContext::current_local_parent())`.

As for creating multiple filtered reporters, this is also currently not supported. However, your use case is interesting and could be a valuable feature for future versions of the library.

**Comment by dotansimha** [comment]
Thank you for the quick reply @andylokandy ! 

> Currently, the library is designed with a single global collector to prioritize performance. This means that configuring distinct collector behaviors for each trace isn't directly supported due to this design trade-off.
> 
> However, it's worth trying out the default configuration to see if it meets your requirements or becomes a performance bottleneck.

I gave it a try and it seems to work fine. I think I can work with a single global collector, as long as I have control over the processing flow (see below)

> Additionally, the [Span::cancel()](https://docs.rs/minitrace/latest/minitrace/struct.Span.html#method.cancel) method does provide some control over trace-level behavior. One possible workaround to achieve multi-tenant tracing could be to split traces of different components into separate roots. You can do this by connecting them with `Span::root("root", SpanContext::current_local_parent())`.

Yeah that's exactly what I planned to do, but I think I might need an additional, custom identifier. The `trace_id` is opaque, so I can't really use that. 

What id `SpanContext` will allow an optional custom value, and it will be rolled with the created Spans (just like `trace_id`)? This should allow me to have an easy way to distinguish what tenant created the Span. 

something like:

```
Span::root("root", SpanContext::with_identifier("/my-endpoint"))
```

This way, I can roll this value: `CollectTokenItem` -> `SpanCollection` -> `SpanRecord`.

> As for creating multiple filtered reporters, this is also currently not supported. However, your use case is interesting and could be a valuable feature for future versions of the library.

As a followup to the section above, if I'll have an easy way to record some metadata/external identifier within the root Span, I should be able to create a wrapping `Reporter` that checks the `SpanRecords` for the metadata, and decides if/where to report the Span.

I gave it a try with a local implementation, and except for some unnecessary `clone`s, it seems like I was able to roll the custom identifier all the way from the root `Span` to the `SpanRecord` in the `Reporter`. I implemented a custom `RouterReporter` that holds multiple other `Reporter` and knows how to route each `Span` to the matching `Reporter`.

This is something you might want to consider in the core implementation @andylokandy? (talking mainly about the metadata/external identifier) If so, I'll be happy to start a PR!

**Comment by dotansimha** [comment]
Also, I think allowing to add custom metadata to the root Span and then roll it to child spans, and then all the way to the `SpanRecord`, should allow users to implement custom use-cases (for example: developers can implement a level filter mechanism, without having that feature implemented in the core of `minitrace` (and address the https://github.com/tikv/minitrace-rust#will-minitrace-incorporate-level-for-spans section)

**Comment by andylokandy** [comment]
t> Yeah that's exactly what I planned to do, but I think I might need an additional, custom identifier. The trace_id is opaque, so I can't really use that.

What id SpanContext will allow an optional custom value, and it will be rolled with the created Spans (just like trace_id)? This should allow me to have an easy way to distinguish what tenant created the Span.

trace_id is not opaque. You can encode tenant information in it. For more complex information, I suggest using  span's [property](https://docs.rs/minitrace/latest/minitrace/struct.Span.html#method.with_property).

> As a followup to the section above, if I'll have an easy way to record some metadata/external identifier within the root Span, I should be able to create a wrapping Reporter that checks the SpanRecords for the metadata, and decides if/where to report the Span.

I think minitrace can solve this problem in other ways. The root span is the key. If you may discard tenants' traces, you must hold the root span of the tenant until the end of processing (otherwise you'll lose span generated after root span has dropped), and you can save the tenant information aside the root span for deciding whether to call `Span::cancel()` at the end.

**Comment by andylokandy** [comment]
> Also, I think allowing to add custom metadata to the root Span and then roll it to child spans, and then all the way to the SpanRecord, should allow users to implement custom use-cases (for example: developers can implement a level filter mechanism, without having that feature implemented in the core of minitrace (and address the https://github.com/tikv/minitrace-rust#will-minitrace-incorporate-level-for-spans section)

You are right. We need some mechanism to turn on/off for different modules and tenant/user. Since this is not included in the specification of OpenTelementry, we are following the specification and let the user take responsibility to keep the information to decide whether to swith tracing on or off. For example, your application could hold a `TenantContext` during the lifetime of processing so that you can call `Span::cancel()` at the end of request processing depending on the `TenantContext` or `Span::elapsed()`.

The behavior change in https://github.com/tikv/minitrace-rust/pull/180 may not suitable for mintrace' initial design, since minitrace are designed to be corporately used by upstream libraries and final application. We should not pass any custom opaque data through. Likewise, we'll not expect the `log` crate doing similar things.

**Comment by dotansimha** [comment]
> trace_id is not opaque. You can encode tenant information in it. For more complex information, I suggest using span's [property](https://docs.rs/minitrace/latest/minitrace/struct.Span.html#method.with_property).

The property is also a great way to do that, but it's limited because it's generated per Span and not inherited from the root (and I didn't see any way to get root info from `SpanRecord` and get access to that span). Also, the data in the properties is being reported, while the data I wish to store as metadata does not leave the application layer and only helps to distinguish spans. 

My idea with the metadata was to pass something that's being inherited to the child spans, like the trace-id. 

And you are right, the `trace_id` is not opaque, but kinda limited because it's configured as `u128`, so I can't really store anything more complex than a numeric value, right? Is there anything else I'm missing here? 
My actual use-case 

> I think minitrace can solve this problem in another way. The root span is the key. If you may discard tenants' traces, you must hold the root span of the tenant until the end of processing (otherwise you'll lose span generated after root span has dropped), and you can keep the tenant information aside the root span for deciding whether to call `Span::cancel()` at the end.

Yeah, that's kinda what I tried to implement. I don't really need to discard Spans, but to redirect them to various `Reporter`s. I was able to achieve that with a custom wrapping `Reporter` that managed multiple other `Reporter`s internally and redirects them to the right place. 

So regarding the initial question I had here: I don't think a global collector is needed.

I managed to implement it using the filtering `Reporter`, and with the Metadata PR I created. If that's not suitable for the `minitrace` approach, I would love to discuss that and see if there's anything else I can do to distinguish `SpanRecord` based on the root Span that created it.

**Comment by andylokandy** [comment]
Ok I get it. You want to group traces, and trace id seems perfect for this case, where you should generate the trace id by encoding the tenant id.

**Comment by dotansimha** [comment]
> Ok I get it. You want to group traces, and trace id seems perfect for this case, where you should generate the trace id by encoding the tenant id.

Yeah this might work. Do you have an example for encoding something like a tenant identifier (string) into a trace-id numeric value? and I assume it needs to be decoded in a similar way to get the value back? 

Also, I'm not sure how an upstream tracing service will handle such case? where multiple traces might have the same trace_id? (or I guess I can decide a random value into the that?)

**Comment by andylokandy** [comment]
In my case, every database session has a query_id (u64), which is appended with a random u64 and then used as trace id. You could do similar by hashing the string to an u32 as the high bits, encoding the reporter group id u32 as the low bits, and at last a random u64. So that you are guaranteed to have a unique trace id, grouped by tenant, and be able to be sorted by the custom reporter.

**Comment by dotansimha** [comment]
> In my case, every database session has a query_id (u64), which is then appended with a random u64 and used as trace id. You could do similar by hashing the string to an u32 as the high bits, encoding the reporter group id u32 as the low bits, then in the end a random u64. So that you are guaranteed to have a unique trace id, grouped by tenant, and be able to be sorted by the custom reporter.

That's a great explanation. I will try to adjust my code to this approach. I can even allocate a const number to each tenant, and it makes it easier to group and generate the eventual identifier. 

> trace id could help you group the traces. If you need the exact tenant id, I suggest using Span::add_property in additionally.

This might still be tricky because I'm not able to add a property to every span, that's why I wanted to add it to the parent. But if I get the same trace-id for the entire Span tree, based on the value defined in the root, it should cover the need to identify the tenant, and I can use that in the `SpanRecord` to distinguish.

Thank you @andylokandy for the support here, I appreciate it! 

I'm also going to close the `Metadata` PR as it's no longer needed with this setup.
