### ISSUE TITLE
loose strict dependency version for `opentelemetry`

### ISSUE THREAD

**Issue by dotansimha** [tikv/minitrace-rust#209]
Right now the versions are pinned (https://github.com/tikv/minitrace-rust/blob/master/minitrace-opentelemetry/Cargo.toml#L19-L20) and doesn't allow a range at all. This makes upgrading other packages very difficult. 
Is it on purpose? or can we consider to make it less strict?

**Comment by andylokandy** [comment]
Sorry for inconvenience, but it's hard to release the version constriant since opentelemetry were changing its API rapidly and we were not able to support a wide range of versions. If you'd like to use a version not supported, I recommend copy and modify in your workspace, since the code base is also relatively small.
